spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dummy@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
